//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSignalRTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatUsers
    {
        public ChatUsers()
        {
            this.ChatContents = new HashSet<ChatContents>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ICollection<ChatContents> ChatContents { get; set; }
    }
}
