//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSignalRTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatContents
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UserName { get; set; }
        public int ChatUser_Id { get; set; }
        public Nullable<int> ChatGroup_Id { get; set; }
    
        public virtual ChatGroups ChatGroups { get; set; }
        public virtual ChatUsers ChatUsers { get; set; }
    }
}
