//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcSignalRTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SignalrDbEntities : DbContext
    {
        public SignalrDbEntities()
            : base("name=SignalrDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Canvas> Canvas { get; set; }
        public DbSet<ChatContents> ChatContents { get; set; }
        public DbSet<ChatGroups> ChatGroups { get; set; }
        public DbSet<ChatUsers> ChatUsers { get; set; }
    }
}
